### ISSUE TITLE
Goland can't recognize Asset

### ISSUE THREAD

**Issue by qianlifeng** [asticode/go-astilectron-demo#24]
Thx for the awesome go-astilectron, it save my days. I have a little question that goland can't recognize Asset variable. I know it's something related to go-bindata, but can't figure how to make it right. 
 
![image](https://user-images.githubusercontent.com/1725475/36675185-4436a48e-1b43-11e8-8425-285266a2782e.png)

**Comment by deranjer** [comment]
This actually doesn't work running it from running "go run main.go".  Take a look at the readme for how to actually run it, basically remove the bind.go file (not sure why it is there?) and then use the astilectron-bundler to bundle the app to an executable, and you can run it from there.  Not the most pleasant experience...

**Comment by deranjer** [comment]
@asticode I understand the IDE not parsing it correctly, but running `go run main.go` doesn't work either, the go runtime returns the error that Asset is undefined (and two other variables as well).  I found that strange as well since bind.go was present, was part of the same package but go run still complained about it...

Currently I'm just using the bundler to bundle my app for testing so not a big deal for me personally.

**Comment by asticode** [comment]
@deranjer when you use `go run`, you have to list all the files you need afterwards, that's why it throws an error. If you run `go run *.go` instead, it should work

**Comment by deranjer** [comment]
Sigh... of course it does... not sure how I forgot about that.. one of those days I guess..
