### ISSUE TITLE
Find a better communication interface between GO and JS

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron-demo#4]
i can use AdaptRouter or analog  new version api?

**Comment by asticode** [comment]
@deepch I've removed the `AdaptRouter` option since I don't think this is a good idea to spawn an additionnal web server since a TCP server is already running to enable communication between `Astilectron` and `Electron`.

I think this is better to use the remote messaging instead since this is a real 2-ways communication:
- you can use `w.Send` to send a message from GO to the Javascript
- or `astilectron.send` to send a message from Javascript to GO

If you use the bootstrap, you can get an HTTP-like communication (meaning a callback is called once the response has been received) by running in your javascript something like [here](https://github.com/asticode/go-astilectron-demo/blob/master/resources/app/static/js/index.js#L25).

I know it means changing some stuff in your awesome project and I really apologize for that, but I think this is for the greater good :)

**Comment by deepch** [comment]
thx i try work astilectron.send

**Comment by deepch** [comment]
Maybe I'm completely noob (but it's very hard to work with only  

astilectron.send({"name": "get.list"}...

before, I just used ajax get method for table https://datatables.net

      'autoWidth'   : false,
      "ajax": "/api/cloud/device/list",


new version i need  use astilectron.send({"name": "get.list"}

      need recive data to dataSet  astilectron.send({"name": "get.list"}
      data: dataSet,

data - not supported dynamic loading need stop or draw table row by row

it will be very uncomfortable to update to load as normal variables.

It's just less convenient than just a web server when there are a lot of plug-ins.


there is no way to emulate get / post and route it?

**Comment by deepch** [comment]
let's say that without methods GET and POST it is much more difficult to work with ready-made plug-ins to find solutions to many problems.
But if you think that it should be so. I will do it but it's not very convenient.

**Comment by asticode** [comment]
@deepch with your current example and as you've already started working with a server I do agree with you it seems way better to stick with the web server.

What I recommend is simply spawn your own server before starting `astilectron` and send its address to the JS with `astilectron.send`. That would look something like that:

```go
// Init
flag.Parse()
astilog.FlagInit()

// Init router
var r = httprouter.New()

// TODO Add your routes here

// Listen
var ln net.Listener
var err error
if ln, err = net.Listen("tcp", "127.0.0.1:"); err != nil {
	astilog.Fatal(err)
}

// Serve
go http.Serve(ln, r)

// Run bootstrap
	if err := bootstrap.Run(bootstrap.Options{
		Homepage: "index.html",
		MessageHandler: handleMessages,
		OnWait: func(_ *astilectron.Astilectron, w *astilectron.Window, _ *astilectron.Menu, t *astilectron.Tray, _ *astilectron.Menu) error {
			// Send server addr to js
                        w.Send(ln.Addr().String())
		},
		WindowOptions: &astilectron.WindowOptions{
			BackgroundColor: astilectron.PtrStr("#333"),
			Center:          astilectron.PtrBool(true),
			Height:          astilectron.PtrInt(600),
			Width:           astilectron.PtrInt(600),
		},
	}); err != nil {
		astilog.Fatal(errors.Wrap(err, "running bootstrap failed"))
}
```

**Comment by asticode** [comment]
But for others, I'd really recommend sticking with remote messaging. If I can do anything to make it more accessible and more easy to work with, feel free to propose an implementation, I'd be happy to add it :)

**Comment by deepch** [comment]
it seemed to me earlier that it was part of one
strangely it seemed to me earlier it worked as part of the current server.
The option you suggested is good but I'm not sure that it is correct.

Is it possible to add routers to the current server?

/index.html
/api/scan/local

as it was before.

**Comment by deepch** [comment]
I made  in astilectron.send({"name": "get.list"}
but it seems to me with GET would still be more convenient.

    astilectron.send({"name": "get.scan"}, function(message) {
      $('#tableONVIF').DataTable({
        "data": jQuery.parseJSON(message.payload).data,
....

But if this is not right I will do as you see fit.

**Comment by joeblew99** [comment]
I am also chewing over this too. I just started using this for 2 hours but see the same problem for myself.

My golang dB and message queue run on all desktops and mobiles.
I use NATS for bidirectional messaging between clients and servers. It uses telnet :) but you can wrap it to use TCP or WAS or Anything 

It might be relevant but not sure if appropriate yet. Still chewing on it

**Comment by deepch** [comment]
im use custom server


func StartAPIServer() {

	var r = httprouter.New()
	r.GET("/scan", APIScan)
	r.GET("/scanrs", APIScanRange)
	var ln net.Listener
	var err error
	if ln, err = net.Listen("tcp", "127.0.0.1:3378"); err != nil {
		astilog.Fatal(err)
	}
	go http.Serve(ln, r)
}


and call ajax

      "ajax": "http://127.0.0.1:3378/scan",


it's ugly but very convenient.

**Comment by asticode** [comment]
I'm also not satisfied with the way `go-astilectron` provides communication interfaces between GO and JS right now to be honest.

I really don't like the idea of spawning an HTTP server since you can't send a message from GO to JS with that method. And I think this is important to have **only one** communication interface between GO and JS.

@joeblew99 you said "I just started using this for 2 hours but see the same problem for myself", can you elaborate a bit, that may give us some good insights on how to resolve this.

**Comment by joeblew99** [comment]
@asticode 

GRPC can now handle web sockets and the JS side can also handle them.
What htis gets you is a way to do http and WS between JS and golang, with lots of code gen.
Its 100% golang and this is a simple example:
https://github.com/johanbrandhorst/grpcweb-example

This method of communications can also be used for all business use cases and not just for the platform communications for Electron perhaps ?

**Comment by deepch** [comment]
I'm generally for an http server that it could be optionally available to anyone who needs it.

**Comment by joeblew99** [comment]
i tend to agree. keep it simple.
the only thing i did not like was the way you wire up the electron comms as a monolithic thing currently. As your project gets bigger it becomes a huge monolith.

**Comment by asticode** [comment]
@joeblew99 do get deeper into `astilectron`'s code, I'm welcoming any qualified comments :)

**Comment by asticode** [comment]
Moving this issue to [go-astilectron](https://github.com/asticode/go-astilectron/issues/55)
