### ISSUE TITLE
Add a GO "Log" method that executes "console.log"

### ISSUE THREAD

**Issue by deepch** [asticode/go-astilectron-demo#6]
I suggest adding console.log() output stdout and stderr from golang 
if this would be possible then debugging would be easier.

In my case, I have a problem in the finished package but I do not have it go run *.go
and without writing processing I will not understand where it is, if it was part of astilectron options.

**Comment by asticode** [comment]
@deepch do you need a `Log()` in GO that would execute a `console.log()` in JS ? Is that it ?

**Comment by deepch** [comment]
yes

**Comment by asticode** [comment]
will do

**Comment by asticode** [comment]
@deepch I've added a GO `window.Log(message string) error` method. Here's what you need to do in order to use it:

- as `astilectron`'s version has been bumped, you need to reinstall the bundler. In order to do that do the following:

```
$ cd $GOPATH/src/github.com/asticode/go-astilectron-bundler
$ make
```

- you need to fetch updated versions:

```
$ cd <your project path>
$ go get -u ./...
```

- use it in your code:

```go
w.Log("my log message")
```

Does that fix your problem and can we close this issue?

**Comment by nkbai** [comment]
is console.log redirect to stdout or stderr?
