### ISSUE TITLE
Custom Titlebar

### ISSUE THREAD

**Issue by roociferSonOfTheMorning** [asticode/go-astilectron-demo#67]
I am looking for some guidance for a custom titlebar. 
Something similar to [custom-electron-titlebar](https://github.com/AlexTorresSk/custom-electron-titlebar) but simpler.
I am specifically looking for drag, min, max and close. 

I've seen a few tickets within your astilectron projects the make me think other people are doing something like this. 

Could you provide some guidance on how I would build this or maybe you know of someone who has a public project with this implemented?

Thank you for your time!

**Comment by asticode** [comment]
I don't see how you can add this directly in electron. However, if I were you, I would implement it in HTML/JS/CSS since in JS you have access to nodeJS functions and the window object

**Comment by roociferSonOfTheMorning** [comment]
I am wanting to implement in html/js/css, I am a little confused as how to get started.

**Comment by roociferSonOfTheMorning** [comment]
if I were to follow a tutorial like this: 
https://github.com/binaryfunt/electron-seamless-titlebar-tutorial

How would I go about controlling the window in [step 8](https://github.com/binaryfunt/electron-seamless-titlebar-tutorial#8-implement-window-controls-functionality) using the astilectron object in js?

**Comment by roociferSonOfTheMorning** [comment]
should I send a message and handle it in the MessageHandler where I have access to the window or is there a way of manipulating the window in javascript?

**Comment by asticode** [comment]
Right now you can use the code in [step 8](https://github.com/binaryfunt/electron-seamless-titlebar-tutorial#8-implement-window-controls-functionality) since you still have access to the `remote` attribute. However, this attribute is deprecated and will be removed in next Electron versions.

Therefore, if I were you, I'd do it the way you've described in your last comment : send a message to GO and let it do the proper action on the window.

**Comment by roociferSonOfTheMorning** [comment]
Thank you very much for your help, I've got it working this morning!
