### ISSUE TITLE
How to set taskbar icon?

### ISSUE THREAD

**Issue by linclt** [asticode/go-astilectron-demo#74]
I want to change this icon on the task bar 
![image](https://user-images.githubusercontent.com/46485507/141443829-adcb07f3-cc3a-45a3-86df-ea3f853a2f3a.png)

and I find the Icon when use absolute path like this :C:/Users/Administrator/go/src/go-electron/resources/icon.ico
,it works. but when i copy the exe to another computer,because there is no icon.ico at C:/Users/Administrator/go/src/go-electron/resources/icon.ico,so the icon change to the electron icon
![image](https://user-images.githubusercontent.com/46485507/141443768-1d742a91-847a-4b33-adac-6928b1fcb3f4.png)
what i can do to solve this problem?

**Comment by asticode** [comment]
Right now there's no solution for that.

The following change would be needed in the lib : `bootstrap.Window.Options` should be `func(a *astilectron.Astilectron) *bootstrap.WindowOptions` instead of `*boostrap.WindowOptions` directly, so that you can use `a.Paths().DataDirectory()` when setting your absolute icon path.

But I won't have time to work on this issue anytime soon.

**Comment by linclt** [comment]
> Right now there's no solution for that.
> 
> The following change would be needed in the lib : `bootstrap.Window.Options` should be `func(a *astilectron.Astilectron) *bootstrap.WindowOptions` instead of `*boostrap.WindowOptions` directly, so that you can use `a.Paths().DataDirectory()` when setting your absolute icon path.
> 
> But I won't have time to work on this issue anytime soon.

Thanks a lot! I will have a try myself!
